import os

ACCESS_TOKEN = os.environ.get('PAGE_ACCESS_TOKEN', None)
VERIFY_TOKEN = os.environ.get('VERIFY_TOKEN', None)
ACCESS_TOKEN_TEST = os.environ.get('TEST_ACCESS_TOKEN', None)

DOC_MAX_LENGTH = 8
TYPE_MESSAGE = 'message'
TYPE_MESSAGE_CODE = 1
TYPE_POSTBACK = 'postback'
TYPE_POSTBACK_CODE = 2